FILE_SELECT_BY_OWNER_PATH = (
    "SELECT\n"
    "    id,\n"
    "    current_version\n"
    "FROM files\n"
    "WHERE owner_id = ?\n"
    "  AND logical_path = ?"
)
FILE_INSERT = (
    "INSERT INTO files(\n"
    "    owner_id,\n"
    "    logical_path,\n"
    "    current_version,\n"
    "    is_deleted,\n"
    "    created_at,\n"
    "    updated_at\n"
    ")\n"
    "VALUES (\n"
    "    ?,\n"
    "    ?,\n"
    "    0,\n"
    "    0,\n"
    "    ?,\n"
    "    ?\n"
    ")"
)
FILE_RESET_CURRENT_VERSION = (
    "UPDATE file_versions\n"
    "SET\n"
    "    is_current = 0\n"
    "WHERE file_id = ?"
)
FILE_INSERT_VERSION = (
    "INSERT INTO file_versions(\n"
    "    file_id,\n"
    "    version_no,\n"
    "    object_name,\n"
    "    size,\n"
    "    etag,\n"
    "    content_type,\n"
    "    created_by,\n"
    "    created_at,\n"
    "    is_current\n"
    ")\n"
    "VALUES (\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    1\n"
    ")"
)
FILE_UPDATE_AFTER_UPLOAD = (
    "UPDATE files\n"
    "SET\n"
    "    current_version = ?,\n"
    "    is_deleted = 0,\n"
    "    deleted_at = NULL,\n"
    "    updated_at = ?\n"
    "WHERE id = ?"
)
FILE_SELECT_META_BY_ID = (
    "SELECT\n"
    "    owner_id,\n"
    "    logical_path,\n"
    "    current_version,\n"
    "    is_deleted\n"
    "FROM files\n"
    "WHERE id = ?"
)
FILE_UPDATE_VERSION_COUNTER = (
    "UPDATE files\n"
    "SET\n"
    "    current_version = ?,\n"
    "    updated_at = ?\n"
    "WHERE id = ?"
)
FILE_LIST_INCLUDE_DELETED = (
    "SELECT\n"
    "    id,\n"
    "    logical_path,\n"
    "    current_version,\n"
    "    is_deleted,\n"
    "    deleted_at,\n"
    "    updated_at\n"
    "FROM files\n"
    "WHERE owner_id = ?\n"
    "  AND logical_path LIKE ?\n"
    "ORDER BY logical_path ASC"
)
FILE_LIST_ACTIVE = (
    "SELECT\n"
    "    id,\n"
    "    logical_path,\n"
    "    current_version,\n"
    "    is_deleted,\n"
    "    deleted_at,\n"
    "    updated_at\n"
    "FROM files\n"
    "WHERE owner_id = ?\n"
    "  AND is_deleted = 0\n"
    "  AND logical_path LIKE ?\n"
    "ORDER BY logical_path ASC"
)
FILE_LIST_SHARED = (
    "SELECT DISTINCT\n"
    "    f.id,\n"
    "    f.logical_path,\n"
    "    f.current_version,\n"
    "    f.updated_at\n"
    "FROM files f\n"
    "LEFT JOIN file_permissions uperm\n"
    "    ON uperm.file_id = f.id\n"
    " AND uperm.subject_type = 'user'\n"
    " AND uperm.subject_id = ?\n"
    " AND uperm.can_read = 1\n"
    "LEFT JOIN file_permissions pperm\n"
    "    ON pperm.file_id = f.id\n"
    " AND pperm.subject_type = 'public'\n"
    " AND pperm.can_read = 1\n"
    "LEFT JOIN group_members gm\n"
    "    ON gm.user_id = ?\n"
    "LEFT JOIN file_permissions gperm\n"
    "    ON gperm.file_id = f.id\n"
    " AND gperm.subject_type = 'group'\n"
    " AND gperm.subject_id = gm.group_id\n"
    " AND gperm.can_read = 1\n"
    "WHERE f.owner_id != ?\n"
    "  AND f.is_deleted = 0\n"
    "    AND (uperm.id IS NOT NULL OR pperm.id IS NOT NULL OR gperm.id IS NOT NULL)\n"
    "ORDER BY f.updated_at DESC"
)
FILE_EXISTS_BY_ID = (
    "SELECT\n"
    "    id\n"
    "FROM files\n"
    "WHERE id = ?"
)
FILE_SELECT_VERSIONS = (
    "SELECT\n"
    "    id,\n"
    "    version_no,\n"
    "    object_name,\n"
    "    size,\n"
    "    etag,\n"
    "    content_type,\n"
    "    created_at,\n"
    "    is_current\n"
    "FROM file_versions\n"
    "WHERE file_id = ?\n"
    "ORDER BY version_no DESC"
)
FILE_SELECT_CURRENT_OBJECT = (
    "SELECT\n"
    "    fv.object_name\n"
    "FROM files f\n"
    "JOIN file_versions fv ON fv.file_id = f.id\n"
    "                     AND fv.is_current = 1\n"
    "WHERE f.id = ?\n"
    "  AND f.is_deleted = 0"
)
FILE_TRASH = (
    "UPDATE files\n"
    "SET\n"
    "    is_deleted = 1,\n"
    "    deleted_at = ?,\n"
    "    updated_at = ?\n"
    "WHERE id = ?"
)
FILE_LIST_TRASH = (
    "SELECT\n"
    "    id,\n"
    "    logical_path,\n"
    "    deleted_at\n"
    "FROM files\n"
    "WHERE owner_id = ?\n"
    "  AND is_deleted = 1\n"
    "ORDER BY deleted_at DESC"
)
FILE_RESTORE = (
    "UPDATE files\n"
    "SET\n"
    "    is_deleted = 0,\n"
    "    deleted_at = NULL,\n"
    "    updated_at = ?\n"
    "WHERE id = ?"
)
FILE_SELECT_DELETED_FLAG = (
    "SELECT\n"
    "    is_deleted\n"
    "FROM files\n"
    "WHERE id = ?"
)
FILE_UPDATE_PERMISSION = (
    "UPDATE file_permissions\n"
    "SET\n"
    "    can_read = ?,\n"
    "    can_upload = ?,\n"
    "    can_manage = ?,\n"
    "    created_by = ?,\n"
    "    created_at = ?\n"
    "WHERE file_id = ?\n"
    "  AND subject_type = ?\n"
    "  AND subject_id = ?"
)
FILE_INSERT_PERMISSION = (
    "INSERT INTO file_permissions(\n"
    "    file_id,\n"
    "    subject_type,\n"
    "    subject_id,\n"
    "    can_read,\n"
    "    can_upload,\n"
    "    can_manage,\n"
    "    created_by,\n"
    "    created_at\n"
    ")\n"
    "VALUES (\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?\n"
    ")"
)
FILE_INSERT_SHARE = (
    "INSERT INTO shares(\n"
    "    token,\n"
    "    file_id,\n"
    "    created_by,\n"
    "    expires_at,\n"
    "    password_hash,\n"
    "    allow_download,\n"
    "    created_at,\n"
    "    one_time,\n"
    "    max_downloads,\n"
    "    allow_upload\n"
    ")\n"
    "VALUES (\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?\n"
    ")"
)
