FOLDER_INSERT = (
    "INSERT INTO folders(\n"
    "    owner_id,\n"
    "    path,\n"
    "    created_at\n"
    ")\n"
    "VALUES (\n"
    "    ?,\n"
    "    ?,\n"
    "    ?\n"
    ")"
)
FOLDER_SELECT_BY_OWNER_PATH = (
    "SELECT\n"
    "    owner_id\n"
    "FROM folders\n"
    "WHERE owner_id = ?\n"
    "  AND path = ?"
)
FOLDER_UPDATE_PERMISSION = (
    "UPDATE folder_permissions\n"
    "SET\n"
    "    can_read = ?,\n"
    "    can_upload = ?,\n"
    "    can_manage = ?,\n"
    "    created_by = ?,\n"
    "    created_at = ?\n"
    "WHERE owner_id = ?\n"
    "  AND folder_path = ?\n"
    "  AND subject_type = ?\n"
    "  AND subject_id = ?"
)
FOLDER_INSERT_PERMISSION = (
    "INSERT INTO folder_permissions(\n"
    "    owner_id,\n"
    "    folder_path,\n"
    "    subject_type,\n"
    "    subject_id,\n"
    "    can_read,\n"
    "    can_upload,\n"
    "    can_manage,\n"
    "    created_by,\n"
    "    created_at\n"
    ")\n"
    "VALUES (\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?,\n"
    "    ?\n"
    ")"
)
FOLDER_SELECT_FILES_FOR_APPLY = (
    "SELECT\n"
    "    id,\n"
    "    logical_path\n"
    "FROM files\n"
    "WHERE owner_id = ?\n"
    "  AND logical_path LIKE ?\n"
    "  AND is_deleted = 0"
)
